### ISSUE TITLE
リアルタイムの仮実装

### ISSUE THREAD

**Issue by yugo-ibuki** [Qin-Eva/pj_engivia#47]
適当なデータでいいので、リアルタイムでの変更を反映できるかのテスト、調査をお願いしたいです。
supabaseでは、subscribeというのが用意されているようで、そちらを使用するとリアルタイムでの反映が可能になるらしいので
firestoreでもそういった機能はあるかと思います。
軽く試してみて欲しいです。

参考:
https://firebase.google.com/docs/firestore/query-data/listen

**Comment by kijikunnn** [comment]
@yugo-ibuki 
投稿一覧ページでテストをしていたのですが，テストはどのページのどのデータでも
リアルタイムでの変更を反映できるかを確認できれば良いですか？

**Comment by yugo-ibuki** [comment]
@kijikunnn 
1つ検証できれば、大丈夫です！
検証用にテーブル（コレクション）作っちゃってもいいですよ〜
お願いします〜！
